language: node_js
node_js: 10.16.0
cache:
  directories:
    - node_modules
install:
  - yarn install
  - yarn build
deploy:
  - provider: s3
    acl: public_read
    bucket: billfeng.io
    local_dir: build
    region: ap-northeast-1
    skip_cleanup: true
